### model
model_name_or_path: meta-llama/Llama-3.2-1B-Instruct
trust_remote_code: true

### method
stage: kto
do_train: true
finetuning_type: lora

# LoRA settings
lora_rank: 8        # matches "LoRA Rank: 8"
lora_alpha: 16      # matches "LoRA Î±: 16"
lora_dropout: 0.0   # matches "LoRA Dropout: 0.0"
lora_target: all
pref_beta: 0.1

### dataset
dataset: gsm8k_training_negative_kto
template: llama3
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/llama3-2-1b/lora/kto
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true
dataloader_pin_memory: false
push_to_hub: true
hub_model_id: EleanorZzz/gsm8k_training_negative_kto

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
